// Não adicione o "use client" aqui, pois estamos lidando com o lado do servidor
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Rodape from "./components/Rodape";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dev Peter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ backgroundColor: "rgb(var(--background))" }}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Rodape />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
